server:
  port: 8086
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  elasticsearch:
    rest:
      uris: http://39.105.153.243:9200
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
    host: 39.105.153.243
    virtual-host: /anlin
    username: anlin
    password: anlin
